### ISSUE TITLE
Version on pypi.org is outdated

### ISSUE THREAD

**Issue by Bahnburner** [sentry07/DirectPy#9]
The version that installs from pypi.or using pip3 is outdated and returns errors when using the clientAddr variable. Pulling the current version from github resolves this issue. 

Would it be possible to update the version on pypi, as my current work around is to reinstall into my docker container after every homeassistant update. 

Thanks.

**Comment by sentry07** [comment]
Weird. What I see on PyPi is version 0.2 and that's what's on GitHub as
well. What version do you get from pip3?

**Comment by Bahnburner** [comment]
Both report version 0.2, but when using the clientAddr variable the pypi version returns

```
>>> from DirectPy import DIRECTV
>>> dtv = DIRECTV('10.0.0.151',clientAddr='88F7C7A17C19')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/DirectPy.py", line 33, in __init__
    self.get_tuned()
  File "/usr/local/lib/python3.6/site-packages/DirectPy.py", line 74, in get_tuned
    self.channel = self._combine_channel(jResp['major'],jResp['minor'])
KeyError: 'major'
```
The github version works as expected. 

Diffing the pypi and github versions returns: 
```
root@titan-ubuntu:/usr/local/lib/python3.6/site-packages# diff DirectPy-PyPi.py DirectPy-GitHub.py
57c57,61
<         if jResp['status']['code'] == 200:
---
>
>         """Handle clientAddrs that are offline/not reporting for some reason"""
>         if jResp['status']['code'] == 403:
>             self.standby = 1
>         else:
74c78,79
<         self.channel = self._combine_channel(jResp['major'],jResp['minor'])
---
>         if jResp['status']['code'] == 200:
>             self.channel = self._combine_channel(jResp['major'],jResp['minor'])
```

**Comment by sentry07** [comment]
I've submitted v0.3 to pypi with the current version of code from GitHub. Please upgrade your install via pip and verify the class header says DirectPy.py v0.3 by Eric Walters (github.com/sentry07)

**Comment by sentry07** [comment]
Note that if you're doing it through pip, you may have to use the --no-cache-dir option so it won't reinstall the old version.

**Comment by Bahnburner** [comment]
That fixed it. Thanks!

**Comment by sentry07** [comment]
So I made another update to try to help with HomeAssistant, screwed up a couple times, and now directpy is at version 0.5 on PyPi if you want to update to that version and test to make sure it still works. I tried to update the package requirement in HomeAssistant's module and someone yelled at me for not using a template in the pull request so I'll let somebody else do it.

**Comment by Bahnburner** [comment]
Tested and working. I'll submit an issue to the Home-Assistant folks.

**Comment by Bahnburner** [comment]
Well, I submitted a pull request, used their template and jumped through their hoops. All of the tests passed, so it looks like the PR should be merged shortly. Thanks for all your help today!
